version: "3.8"

# matainter 'shanezhiu <shanezhiu@gmail.com>'

services: 
    web:
        build: nginx
        depends_on: 
            - php-fpm
            - php7.1-fpm
        working_dir: /apps
        volumes: 
            - "./apps:/apps"
            - "./nginx/conf.d:/etc/nginx/conf.d"
            - "./nginx/ssl:/etc/nginx/ssl"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./logs/nginx:/var/log/nginx"
        expose: 
            - 80
            - 81
        ports: 
            - "8080:80"
        restart: "always"
        networks: 
            web_service:
                ipv4_address: 172.27.0.2
                ipv6_address: 2001:3984:3989::10

    php-fpm:
        build: php-fpm/7.4
        working_dir: /apps
        depends_on: 
            - db
            - redis
            - memcached
        volumes: 
            - "./apps/:/apps"
            - "./logs/php-fpm:/var/logs/php"
            - "./php-fpm/7.4/conf:/usr/local/etc"
        expose: 
            - 9000
            - 9005
        restart: "always"
        networks: 
            web_service:
                ipv4_address: 172.27.0.3
                ipv6_address: 2001:3984:3989::11

    php7.1-fpm:
        build: php-fpm/7.1
        working_dir: /apps
        environment: 
            http_proxy: ''
            https_proxy: ''
            HTTP_PROXY: ''
            HTTPS_PROXY: ''
        depends_on: 
            - db
            - redis
            - memcached
        volumes: 
            - "./apps/:/apps"
            - "./logs/php-fpm:/var/logs/php"
            - "./php-fpm/7.1/conf/php.ini:/usr/local/etc/php/php.ini"
            - "./php-fpm/7.1/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf"
            - "./php-fpm/7.1/conf/php-fpm.d:/usr/local/etc/php-fpm.d"
        expose: 
            - 9000
            - 9005
        restart: "always"
        networks: 
            web_service:
                ipv4_address: 172.27.0.4
                ipv6_address: 2001:3984:3989::12

    db:
        build: database/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=shanechioa
        volumes: 
            - "./database/mysql/conf:/etc/mysql/conf.d"
            - "./logs/mysql:/var/logs/mysql"
            - "./data/mysql:/data/mysql"
        expose: 
            - 3306
            - 33060
        restart: "always"
        networks: 
            web_service:
                ipv4_address: 172.27.0.5
                ipv6_address: 2001:3984:3989::13
    mongo:
        build: database/mongo
        restart: "always"
        expose: 
            - "27017"
            - "27016"
        ports:
            - "27016:27017"
        volumes: 
            - "./database/mongo/conf/mongod.conf:/etc/mongod.conf"
            - "./data/mongo:/var/lib/mongodb"
            - "./logs/mongo:/var/log/mongodb"    
        networks: 
            web_service:
                ipv4_address: 172.27.0.9
                ipv6_address: 2001:3984:3989::17
    redis:
        build: database/redis
        restart: "always"
        volumes: 
            - "./database/redis/conf.d/redis.conf:/etc/redis.conf"
            - "./data/redis:/var/lib/redis"
            - "./logs/redis:/var/lib/logs"
        ports:
            - "6378:6378"
        networks: 
            web_service:
                ipv4_address: 172.27.0.6
                ipv6_address: 2001:3984:3989::14

    memcached:
        build: cache/memcached
        restart: "always"
        networks: 
            web_service:
                ipv4_address: 172.27.0.7
                ipv6_address: 2001:3984:3989::15

networks: 
    web_service:
        driver: bridge
        ipam:
            config:
                - subnet: "172.27.0.0/16"
                - subnet: "2001:3984:3989::/64"
